name: "Dashbuild SonarQube"
description: "Fetch SonarQube/SonarCloud metrics and generate a report page for Dashbuild"

inputs:
  token:
    description: "SonarQube/SonarCloud API token. Required unless data-file is set."
    required: false
    default: ""
  host-url:
    description: "SonarQube server URL"
    required: false
    default: "https://sonarcloud.io"
  project-key:
    description: "SonarQube project key. Required unless data-file is set. Falls back to sonar.projectKey from sonar-project.properties."
    required: false
    default: ""
  organization:
    description: "SonarCloud organization key. Falls back to sonar.organization from sonar-project.properties."
    required: false
    default: ""
  metrics:
    description: "Comma-separated list of metric keys to fetch from the API"
    required: false
    default: "bugs,vulnerabilities,code_smells,coverage,duplicated_lines_density,ncloc,security_hotspots,reliability_rating,security_rating,sqale_rating"
  areas:
    description: "Comma-separated metric areas to display. Default: coverage,duplicated_lines_density,code_smells,bugs,vulnerabilities,sqale_rating. Opt-in extras: ncloc,reliability_rating,security_rating,security_hotspots"
    required: false
    default: "coverage,duplicated_lines_density,code_smells,bugs,vulnerabilities,sqale_rating"
  cache-key:
    description: "GitHub Actions cache key for historical data. Set to enable data-over-time tracking. Example: dashbuild-sonarqube-history"
    required: false
    default: ""
  retention-days:
    description: "Number of days of historical data to keep. Entries older than this are pruned before caching. 0 = keep all. Default: 90"
    required: false
    default: "90"
  data-file:
    description: "Path to a pre-built JSON data file. When set, the API fetch is skipped and this file is used directly. Intended for development, demos, and CI self-testing where real SonarQube credentials are unavailable."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Use pre-built data file
      if: inputs.data-file != ''
      shell: bash
      run: |
        SLUG=$(node -e "console.log(JSON.parse(require('fs').readFileSync('${{ github.action_path }}/module.json','utf-8')).slug)")
        TARGET="${DASHBUILD_DIR}/src/data/${SLUG}.json"
        mkdir -p "$(dirname "${TARGET}")"
        cp "${{ inputs.data-file }}" "${TARGET}"
        echo "::notice::Using pre-built data file: ${{ inputs.data-file }}"

    - name: Restore historical data from cache
      if: inputs.data-file == '' && inputs.cache-key != ''
      uses: actions/cache/restore@v4
      with:
        path: .dashbuild-sonarqube-cache
        key: ${{ inputs.cache-key }}

    - name: Read sonar-project.properties
      if: inputs.data-file == ''
      id: sonar-props
      shell: bash
      run: |
        PROPS_FILE="${GITHUB_WORKSPACE}/sonar-project.properties"
        if [ -f "${PROPS_FILE}" ]; then
          echo "::notice::Found sonar-project.properties"
          KEY=$(grep -E '^sonar\.projectKey=' "${PROPS_FILE}" | head -1 | cut -d= -f2-)
          ORG=$(grep -E '^sonar\.organization=' "${PROPS_FILE}" | head -1 | cut -d= -f2-)
          echo "project-key=${KEY}" >> "$GITHUB_OUTPUT"
          echo "organization=${ORG}" >> "$GITHUB_OUTPUT"
        fi

    - name: Fetch SonarQube metrics
      if: inputs.data-file == ''
      shell: bash
      env:
        SONAR_TOKEN: ${{ inputs.token }}
        SONAR_HOST_URL: ${{ inputs.host-url }}
        SONAR_PROJECT_KEY: ${{ inputs.project-key || steps.sonar-props.outputs.project-key }}
        SONAR_ORGANIZATION: ${{ inputs.organization || steps.sonar-props.outputs.organization }}
        SONAR_METRICS: ${{ inputs.metrics }}
        SONAR_AREAS: ${{ inputs.areas }}
        SONAR_CACHE_FILE: ${{ inputs.cache-key != '' && '.dashbuild-sonarqube-cache/sonarqube.json' || '' }}
        SONAR_RETENTION_DAYS: ${{ inputs.retention-days }}
      run: |
        bash "${{ github.action_path }}/scripts/fetch-sonarqube.sh"

    - name: Save historical data to cache
      if: inputs.data-file == '' && inputs.cache-key != ''
      uses: actions/cache/save@v4
      with:
        path: .dashbuild-sonarqube-cache
        key: ${{ inputs.cache-key }}-${{ github.run_id }}

    - name: Generate report page
      shell: bash
      run: node "${{ github.action_path }}/../_shared/lib/generate-page.js" "${{ github.action_path }}"

    - name: Generate overview
      shell: bash
      run: node "${{ github.action_path }}/scripts/generate-overview.js"

    - name: Register module
      shell: bash
      run: node "${{ github.action_path }}/../_shared/lib/register-module.js" "${{ github.action_path }}"
